// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_Controller
global.__objectDepths[1] = 0; // obj_Startup
global.__objectDepths[2] = 0; // obj_ButtonController
global.__objectDepths[3] = 0; // obj_Score
global.__objectDepths[4] = -1; // obj_Refresh
global.__objectDepths[5] = 0; // obj_Swipe
global.__objectDepths[6] = -200; // obj_LeaveRating
global.__objectDepths[7] = 0; // obj_RainController
global.__objectDepths[8] = 0; // obj_NoiseController
global.__objectDepths[9] = 300; // obj_ControlInverter
global.__objectDepths[10] = 0; // obj_FadeIn
global.__objectDepths[11] = 0; // obj_Choose
global.__objectDepths[12] = 0; // obj_SettingsController
global.__objectDepths[13] = 0; // obj_ChallengeButtonController
global.__objectDepths[14] = 0; // obj_ChallengeController
global.__objectDepths[15] = 0; // obj_ChallengeLabelController
global.__objectDepths[16] = 0; // obj_NextRoom
global.__objectDepths[17] = 0; // obj_Block_Parent
global.__objectDepths[18] = 0; // obj_ShooterParent
global.__objectDepths[19] = -10; // obj_Emitter_Active
global.__objectDepths[20] = -10; // obj_Emitter_Passive
global.__objectDepths[21] = 0; // obj_Zapper
global.__objectDepths[22] = 0; // obj_Demon
global.__objectDepths[23] = 0; // obj_Seeker
global.__objectDepths[24] = 0; // obj_Block_Vert
global.__objectDepths[25] = 0; // obj_Block_Horiz
global.__objectDepths[26] = 0; // obj_Block_Right
global.__objectDepths[27] = 0; // obj_Block_Left
global.__objectDepths[28] = 0; // obj_Shooter_Left
global.__objectDepths[29] = 0; // obj_Shooter_Right
global.__objectDepths[30] = 0; // obj_Shooter_Down
global.__objectDepths[31] = 0; // obj_Shooter_Up
global.__objectDepths[32] = 0; // obj_Flare
global.__objectDepths[33] = -200; // obj_Cloud
global.__objectDepths[34] = 0; // obj_Rain
global.__objectDepths[35] = 0; // obj_Noise
global.__objectDepths[36] = 0; // obj_SeekerDoor
global.__objectDepths[37] = -100; // obj_DoorStop
global.__objectDepths[38] = 0; // obj_HailShooter
global.__objectDepths[39] = -100; // obj_CountDown
global.__objectDepths[40] = -100; // obj_Play
global.__objectDepths[41] = -100; // obj_Replay
global.__objectDepths[42] = 0; // obj_Reset
global.__objectDepths[43] = 0; // obj_Return
global.__objectDepths[44] = 0; // obj_Revert
global.__objectDepths[45] = -100; // obj_Free
global.__objectDepths[46] = 0; // obj_Settings
global.__objectDepths[47] = -100; // obj_Music
global.__objectDepths[48] = -100; // obj_Sound
global.__objectDepths[49] = 0; // obj_Button
global.__objectDepths[50] = 0; // obj_Button_Wide
global.__objectDepths[51] = 0; // obj_About
global.__objectDepths[52] = -200; // obj_AboutDetails
global.__objectDepths[53] = -200; // obj_NoSettings
global.__objectDepths[54] = 0; // obj_Achievement
global.__objectDepths[55] = 0; // obj_Skills
global.__objectDepths[56] = 0; // obj_Upgrade
global.__objectDepths[57] = -400; // obj_NavLeft
global.__objectDepths[58] = -400; // obj_NavRight
global.__objectDepths[59] = -300; // obj_Flash
global.__objectDepths[60] = 0; // obj_SliderRail
global.__objectDepths[61] = -1; // obj_Slider
global.__objectDepths[62] = -100; // obj_FullGame
global.__objectDepths[63] = -100; // obj_SingleMission
global.__objectDepths[64] = 0; // obj_BigButton
global.__objectDepths[65] = 0; // obj_SmallButton
global.__objectDepths[66] = 0; // obj_ChallengeButton
global.__objectDepths[67] = 0; // obj_GameCenter
global.__objectDepths[68] = 0; // obj_Phone
global.__objectDepths[69] = -200; // obj_Star
global.__objectDepths[70] = 0; // obj_TwentyTwinkes
global.__objectDepths[71] = 0; // obj_Rewind
global.__objectDepths[72] = 0; // obj_Restart
global.__objectDepths[73] = 0; // obj_Hash
global.__objectDepths[74] = 0; // obj_Continue
global.__objectDepths[75] = 0; // obj_HintStrip
global.__objectDepths[76] = 0; // obj_Halo
global.__objectDepths[77] = 0; // obj_LanderRed
global.__objectDepths[78] = 0; // obj_Twinkle
global.__objectDepths[79] = -10; // obj_Spiral
global.__objectDepths[80] = 0; // obj_Base
global.__objectDepths[81] = -2; // obj_Lander
global.__objectDepths[82] = 0; // obj_Cushion
global.__objectDepths[83] = 0; // obj_CushounH
global.__objectDepths[84] = 0; // obj_Invincipill
global.__objectDepths[85] = -10; // obj_Pillbox
global.__objectDepths[86] = 0; // obj_InvinciLever
global.__objectDepths[87] = 0; // obj_Mount
global.__objectDepths[88] = 0; // obj_Bouncer
global.__objectDepths[89] = 10; // obj_Target
global.__objectDepths[90] = 0; // obj_BouncerMover
global.__objectDepths[91] = 0; // obj_Umbrella
global.__objectDepths[92] = -100; // obj_Portal
global.__objectDepths[93] = -101; // obj_Portal_In
global.__objectDepths[94] = 0; // obj_LanderTouchParent
global.__objectDepths[95] = -20; // obj_HintRed


global.__objectNames[0] = "obj_Controller";
global.__objectNames[1] = "obj_Startup";
global.__objectNames[2] = "obj_ButtonController";
global.__objectNames[3] = "obj_Score";
global.__objectNames[4] = "obj_Refresh";
global.__objectNames[5] = "obj_Swipe";
global.__objectNames[6] = "obj_LeaveRating";
global.__objectNames[7] = "obj_RainController";
global.__objectNames[8] = "obj_NoiseController";
global.__objectNames[9] = "obj_ControlInverter";
global.__objectNames[10] = "obj_FadeIn";
global.__objectNames[11] = "obj_Choose";
global.__objectNames[12] = "obj_SettingsController";
global.__objectNames[13] = "obj_ChallengeButtonController";
global.__objectNames[14] = "obj_ChallengeController";
global.__objectNames[15] = "obj_ChallengeLabelController";
global.__objectNames[16] = "obj_NextRoom";
global.__objectNames[17] = "obj_Block_Parent";
global.__objectNames[18] = "obj_ShooterParent";
global.__objectNames[19] = "obj_Emitter_Active";
global.__objectNames[20] = "obj_Emitter_Passive";
global.__objectNames[21] = "obj_Zapper";
global.__objectNames[22] = "obj_Demon";
global.__objectNames[23] = "obj_Seeker";
global.__objectNames[24] = "obj_Block_Vert";
global.__objectNames[25] = "obj_Block_Horiz";
global.__objectNames[26] = "obj_Block_Right";
global.__objectNames[27] = "obj_Block_Left";
global.__objectNames[28] = "obj_Shooter_Left";
global.__objectNames[29] = "obj_Shooter_Right";
global.__objectNames[30] = "obj_Shooter_Down";
global.__objectNames[31] = "obj_Shooter_Up";
global.__objectNames[32] = "obj_Flare";
global.__objectNames[33] = "obj_Cloud";
global.__objectNames[34] = "obj_Rain";
global.__objectNames[35] = "obj_Noise";
global.__objectNames[36] = "obj_SeekerDoor";
global.__objectNames[37] = "obj_DoorStop";
global.__objectNames[38] = "obj_HailShooter";
global.__objectNames[39] = "obj_CountDown";
global.__objectNames[40] = "obj_Play";
global.__objectNames[41] = "obj_Replay";
global.__objectNames[42] = "obj_Reset";
global.__objectNames[43] = "obj_Return";
global.__objectNames[44] = "obj_Revert";
global.__objectNames[45] = "obj_Free";
global.__objectNames[46] = "obj_Settings";
global.__objectNames[47] = "obj_Music";
global.__objectNames[48] = "obj_Sound";
global.__objectNames[49] = "obj_Button";
global.__objectNames[50] = "obj_Button_Wide";
global.__objectNames[51] = "obj_About";
global.__objectNames[52] = "obj_AboutDetails";
global.__objectNames[53] = "obj_NoSettings";
global.__objectNames[54] = "obj_Achievement";
global.__objectNames[55] = "obj_Skills";
global.__objectNames[56] = "obj_Upgrade";
global.__objectNames[57] = "obj_NavLeft";
global.__objectNames[58] = "obj_NavRight";
global.__objectNames[59] = "obj_Flash";
global.__objectNames[60] = "obj_SliderRail";
global.__objectNames[61] = "obj_Slider";
global.__objectNames[62] = "obj_FullGame";
global.__objectNames[63] = "obj_SingleMission";
global.__objectNames[64] = "obj_BigButton";
global.__objectNames[65] = "obj_SmallButton";
global.__objectNames[66] = "obj_ChallengeButton";
global.__objectNames[67] = "obj_GameCenter";
global.__objectNames[68] = "obj_Phone";
global.__objectNames[69] = "obj_Star";
global.__objectNames[70] = "obj_TwentyTwinkes";
global.__objectNames[71] = "obj_Rewind";
global.__objectNames[72] = "obj_Restart";
global.__objectNames[73] = "obj_Hash";
global.__objectNames[74] = "obj_Continue";
global.__objectNames[75] = "obj_HintStrip";
global.__objectNames[76] = "obj_Halo";
global.__objectNames[77] = "obj_LanderRed";
global.__objectNames[78] = "obj_Twinkle";
global.__objectNames[79] = "obj_Spiral";
global.__objectNames[80] = "obj_Base";
global.__objectNames[81] = "obj_Lander";
global.__objectNames[82] = "obj_Cushion";
global.__objectNames[83] = "obj_CushounH";
global.__objectNames[84] = "obj_Invincipill";
global.__objectNames[85] = "obj_Pillbox";
global.__objectNames[86] = "obj_InvinciLever";
global.__objectNames[87] = "obj_Mount";
global.__objectNames[88] = "obj_Bouncer";
global.__objectNames[89] = "obj_Target";
global.__objectNames[90] = "obj_BouncerMover";
global.__objectNames[91] = "obj_Umbrella";
global.__objectNames[92] = "obj_Portal";
global.__objectNames[93] = "obj_Portal_In";
global.__objectNames[94] = "obj_LanderTouchParent";
global.__objectNames[95] = "obj_HintRed";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for