    health = global.g_starting_health;
    global.g_fuel= global.g_starting_fuel;
    global.g_is_alive = 1;
    global.g_is_dying = 0;
    global.g_is_dead  = 0;
    global.game_on = 1;
    global.tilt = 0;
    global.room_score = 0;
    global.twinkle_twenty = 0;